<a href="https://colab.research.google.com/github/AhmUmarCMS/AhmuCMS/blob/main/8_PuzzleTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Generating 8-Puzzle from User Input**


In [18]:
def generate_8_puzzle():

    print("Please enter numbers of the 8-Puzzle one-by-one")
    puzzle = []
    puzzle_dimension = [0,1,2]

    for i in puzzle_dimension:
        row = []
        for j in puzzle_dimension:
            while True:

                    num = int(input(f"Enter number for position ({i},{j}): "))
                    if num < 0 or num > 8:
                        print("Number must be between 0 and 8.")
                        continue
                    if num in row:
                        print("Number already exists in this row.")
                        continue
                    row.append(num)
                    break

        puzzle.append(row)
    return puzzle

def print_puzzle(puzzle):
    for row in puzzle:
        print(row)

user_puzzle = generate_8_puzzle()
print_puzzle(user_puzzle)

Please enter numbers of the 8-Puzzle one-by-one
Enter number for position (0,0): 0
Enter number for position (0,1): 2
Enter number for position (0,2): 5
Enter number for position (1,0): 1
Enter number for position (1,1): 7
Enter number for position (1,2): 8
Enter number for position (2,0): 4
Enter number for position (2,1): 6
Enter number for position (2,2): 3
[0, 2, 5]
[1, 7, 8]
[4, 6, 3]


# **Generating 8-Puzzle using Numpy:**

In [20]:
import numpy as np
import random

def generate_random_puzzle():
    numbers = list(range(9))
    random.shuffle(numbers)
    puzzle = np.array(numbers).reshape(3, 3)
    return puzzle

def print_puzzle(puzzle):
    for row in puzzle:
        print(row)


random_puzzle = generate_random_puzzle()


print("Randomly generated 8-puzzle:")
print_puzzle(random_puzzle)

Randomly generated 8-puzzle:
[2 4 1]
[5 6 3]
[8 0 7]
