<a href="https://colab.research.google.com/github/AhmUmarCMS/AhmuCMS/blob/main/GeneticAlgorithm_8Queens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random
import numpy as np

N = 8

def initialize_population(pop_size=10):
    population = []
    for _ in range(pop_size):
        board = np.zeros((N, N))
        for col in range(N):
            row = random.randint(0, N-1)
            board[row, col] = 1
        population.append(board)
    return population

def fitness(board):
    clashes = 0
    for i in range(N):
        for j in range(N):
            if board[i][j] == 1:
                for k in range(N):
                    if k != j and board[i][k] == 1:
                        clashes += 1
                    if k != i and board[k][j] == 1:
                        clashes += 1
                for k in range(1, N):
                    if i+k < N and j+k < N and board[i+k][j+k] == 1:
                        clashes += 1
                    if i-k >= 0 and j+k < N and board[i-k][j+k] == 1:
                        clashes += 1
                    if i+k < N and j-k >= 0 and board[i+k][j-k] == 1:
                        clashes += 1
                    if i-k >= 0 and j-k >= 0 and board[i-k][j-k] == 1:
                        clashes += 1
    return clashes

def selection(population):
    sorted_population = sorted(population, key=fitness, reverse=True)
    return sorted_population[:len(population) // 2]

def crossover(parent_a, parent_b):
    crossover_point = random.randint(1, N-1)
    child_a = np.vstack((parent_a[:crossover_point], parent_b[crossover_point:]))
    child_b = np.vstack((parent_b[:crossover_point], parent_a[crossover_point:]))
    return child_a, child_b

def mutate(board, mutation_rate=0.1):
    if random.random() < mutation_rate:
        col = random.randint(0, N-1)
        row = random.randint(0, N-1)
        board[:, col] = 0
        board[row, col] = 1
    return board

def genetic_algorithm(iterations=1000, pop_size=10):
    population = initialize_population(pop_size)
    for _ in range(iterations):
        selected_population = selection(population)
        new_population = []
        while len(new_population) < pop_size:
            parent_a, parent_b = random.sample(selected_population, 2)
            child_a, child_b = crossover(parent_a, parent_b)
            new_population.append(mutate(child_a))
            new_population.append(mutate(child_b))
        population = new_population
        best_board = max(population, key=fitness)
        if fitness(best_board) == 0:
            break
    return best_board

final_board = genetic_algorithm()
print(final_board)


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
